- name: Install generated public key on Proxmox
  hosts: proxmox
  gather_facts: false
  vars:
    pub_key: "{{ lookup('env','SSH_PUB_KEY') }}"
  tasks:
    - name: Add public key
      ansible.builtin.authorized_key:
        user: root
        key: "{{ pub_key }}"
        state: present