---
- name: Start newly created VMs and login after delay
  hosts: proxmox
  gather_facts: false
  vars_files:
  - ../group_vars/vault.yml
  - ../inventory/group_vars/proxmox.yml
  vars:
    login_command: "whoami"

  tasks:
    - name: Start each VM
      ansible.builtin.shell: qm start {{ item.id }}
      loop: "{{ vault_k8s_masters + vault_k8s_workers }}"
      loop_control:
        label: "Starting {{ item.name }}"

    - name: Wait 5 minutes for VMs to boot and cloud-init to finish
      ansible.builtin.pause:
        minutes: 5

    - name: Attempt SSH login and run command on each VM
      ansible.builtin.shell: ssh -o StrictHostKeyChecking=no {{ vault_ci_user }}@{{ item.ip }} {{ login_command }}
      loop: "{{ vault_k8s_masters + vault_k8s_workers }}"
      loop_control:
        label: "Logging into {{ item.name }}"
      delegate_to: localhost

